options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/monallion-backend:latest"
      - "-f"
      - "Dockerfile"
      - "."

  # Step 2: Push image to Container Registry (or Artifact Registry)
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/monallion-backend:latest"

  # Step 3: Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "monallion-backend"
      - "--image=gcr.io/$PROJECT_ID/monallion-backend:latest"
      - "--platform=managed"
      - "--region=us-central1"
      - "--allow-unauthenticated"
      - "--port=8080"
      - "--quiet"

images:
  - "gcr.io/$PROJECT_ID/monallion-backend:latest"
